# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-06 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='c_address',
            field=models.CharField(default='', max_length=256, verbose_name='c_address'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='c_name',
            field=models.CharField(default='', max_length=256, verbose_name='c_name'),
        ),
    ]
