# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-11 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_auto_20180706_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.IntegerField(verbose_name='plan_id')),
                ('employee_id', models.CharField(default='', max_length=256, verbose_name='employee_id')),
                ('date', models.DateTimeField()),
                ('proportion', models.FloatField(default=0.0, verbose_name='proportion')),
                ('is_allot', models.BooleanField(default=0, verbose_name='is_allot')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=256, verbose_name='number')),
                ('name', models.CharField(default='', max_length=256, verbose_name='name')),
                ('join_date', models.CharField(default='', max_length=256, verbose_name='join_date')),
                ('leave_date', models.CharField(default='', max_length=256, verbose_name='leave_date')),
                ('department', models.CharField(default='', max_length=256, verbose_name='department')),
                ('rank', models.CharField(default='', max_length=256, verbose_name='rank')),
                ('is_finish', models.BooleanField(default=1, verbose_name='is_finish')),
                ('c_number', models.CharField(default='', max_length=256, verbose_name='c_number')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, verbose_name='name')),
                ('start_date', models.DateTimeField()),
                ('validity_time', models.FloatField(default=0.0, verbose_name='validity_time')),
                ('sum', models.FloatField(default=0.0, verbose_name='sum')),
                ('g_time', models.DateTimeField()),
                ('tool', models.CharField(default='', max_length=256, verbose_name='tool')),
                ('count', models.IntegerField(default=0, verbose_name='count')),
            ],
        ),
    ]
