# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_attribution_employee_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(default='', max_length=256, verbose_name='c_id')),
                ('name', models.CharField(default='', max_length=256, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(default='', max_length=256, verbose_name='c_id')),
                ('name', models.CharField(default='', max_length=256, verbose_name='name')),
            ],
        ),
    ]
